# Generated by Django 5.0.3 on 2024-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRestrictionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_folder', models.CharField(max_length=255)),
                ('restriction_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
